version: "3.7"

services:
  flask:
    build: ./server
    container_name: flask
    restart: always
    expose:
      -8080

  nginx:
    build: ./client
    container_name: nginx
    restart: always
    ports:
      -"80":"80"